### ISSUE TITLE
Add `config` parameter to `DashVolumeSlicer` class

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-slicer#6]
This additional parameter would update the `Graph.config` for the Graph of the `DashVolumeSlicer`, which is a way to pass shape drawing tools to be added to the modebar.

**Comment by almarklein** [comment]
I think there are two options:
```py
slicer = VolumeSlicer(app, vol, config={"modeBarButtonsToAdd": ["drawclosedpath", "eraseshape"]})
```
or:
```py
slicer = VolumeSlicer(app, vol)
slicer.graph.config.update({"modeBarButtonsToAdd": ["drawclosedpath", "eraseshape"]})
```

I'm leaning towards the latter, even though it's a bit more work, because it provides a more unified pattern: we create a bunch of Dash components with sensible defaults, which you can tweak afterwards, because you can access them. Unless we can expect users to update `graph.config` much more frequently, to warrant a special argument. What do you think?

In any case, we should document how to do such a thing, and also include it in one of the examples.

**Comment by emmanuelle** [comment]
I'm also more convinced by the second solution! Including it in one of the examples looks like the way to go. Thanks!
